base_url = "https://example.com"
title = "Minimalist"
compile_sass = true
minify_html = true
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
minimalist_date_format = "%Y-%m-%d"
