name = "Minimalist"
description = "Minimalist is content focused, minimal theme for Zola. The theme is perfectly suitable for writers. No JS! CSS only 692B! AAA, 100/100 scores on Lighthouse, Gmetrix and Webpagetest!"
license = "MIT"
homepage = "https://github.com/cydave/zola-theme-minimalist"
min_version = "0.4.0"
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
minimalist_date_format = "%m/%d/%Y"

[author]
name = "cydave"
homepage = "https://github.com/cydave"

[original]
author =  "Ronalds Vilciņš"
homepage = "https://ronalds.eu/"
repo = "https://github.com/ronv/minimalist"
